// react/src/Progress.tsx
interface ProgressProps {
  value: number;
}

function Progress({ value }: ProgressProps) {
  const width = (value * 100).toFixed(2) + '%';

  return (
    <div className='progress'>
      <div className='_inner' style={{ width }}>
        <span className='_text'>{width}</span>
      </div>
    </div>
  );
}

export default Progress;

// vue/src/components/Progress.vue
<script lang="ts">
export default {
  props: ["value"],
  computed: {
    width() {
      return `${(+this.value * 100).toFixed(2)}%`;
    },
  },
};
</script>

<template>
  <div class="progress">
    <div class="_inner" :style="{ width: width }">
      <span class="_text">{{ width }}</span>
    </div>
  </div>
</template>
